### ISSUE TITLE
Device name

### ISSUE THREAD

**Issue by de1phi48** [foroco/php-browser-detection#10]
Good day,

please consider adding a new array element - device_name
`Mozilla/5.0 (Linux; Android 11; M2012K11G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36`
M2012K11G - model of device.

**Comment by netAction** [comment]
The device name would be very helpful in these common cases too:

Ipad:
`Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1`

Iphone:
`Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/216.0.453113025 Mobile/15E148 Safari/604.1`
