### ISSUE TITLE
Error Undefined index for BrowserDetection.php

### ISSUE THREAD

**Issue by sanchezzzhak** [foroco/php-browser-detection#12]
good afternoon

* [ ] IILoader/1.0 CFNetwork/609.1.4 Darwin/12.4.0
Undefined index: 12.6 in Line 733 in File vendor\foroco\php-browser-detection\src\BrowserDetection.php

* [ ] CachedWebView/1.0 CFNetwork/672.1.13 Darwin/13.3.0
Undefined index: 13.4 in Line 733 in File  vendor\foroco\php-browser-detection\src\BrowserDetection.php

**Comment by foroco** [comment]
Hi,

Fixed (see new release).
