### ISSUE TITLE
Snapchat browser is not being detected

### ISSUE THREAD

**Issue by dahleedam** [foroco/php-browser-detection#14]
Hi,

I used your code to detect snapchat browser but it did not detect.
Useragent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15E148 Snapchat/11.68.0.37 (like Safari/8612.3.6.0.4, panda)

**Comment by foroco** [comment]
Hi,

Snapchat has been added (see new release).
