### ISSUE TITLE
Trident based Edge are detect as Chromium based

### ISSUE THREAD

**Issue by Sousa888** [foroco/php-browser-detection#15]
Old versions of Edge are Trident/EdgeHTML based but are detected as Chromium based.
For example this edge useragent (one of the first versions of Edge):
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136
$Browser->getAll returns:
Array
(
    [os_type] => desktop
    [os_family] => windows
    [os_name] => Windows
    [os_version] => 10
    [os_title] => Windows 10
    [device_type] => desktop
    [browser_name] => Edge
    [browser_version] => 12
    [browser_title] => Edge 12
    [browser_chrome_original] => 0
    [browser_firefox_original] => 0
    [browser_safari_original] => 0
    **[browser_chromium_version] => 42**
    [browser_gecko_version] => 0
    [browser_webkit_version] => 0
    [browser_android_webview] => 0
    [browser_ios_webview] => 0
    [browser_desktop_mode] => 0
    [64bits_mode] => 0
)

As it is not based on Chromium, browser_chromium_version should be 0
 **[browser_chromium_version] => 0**

If the last token identifier start whith "Edge/" it is based on Trident if start whith "Edg/" it is based on Chromium.

**Comment by foroco** [comment]
Hi,

You are right. This will be fixed in the next version.

**Comment by foroco** [comment]
Fixed in 2.6
