### ISSUE TITLE
Possibility of having the OS number in addition to the name in mac the same or similar as in windows

### ISSUE THREAD

**Issue by DigitalAndSEO** [foroco/php-browser-detection#19]
Currently we can access `[os_version]` and get the name of the OS (ex: Big sur).
Would it be possible to obtain, in addition to the name, the version number with something similar to `[os_number_version]` ?

Edit:
I just checked in windows and the number does appear (ex: 10, in the case of Windows 10).
Would it be possible to have the same on mac?

Thanks

**Comment by foroco** [comment]
This is possible, but historically it's more common to think of MacOS releases by code name.
I will consider getting additional numerical release names in the future releases.
