### ISSUE TITLE
Version package

### ISSUE THREAD

**Issue by younggrandpa** [foroco/php-browser-detection#2]
Hi @foroco, 

I hope you're well. 

I got this warning from "composer":  I added `"foroco/php-browser-detection": "dev-master"` in my composer.json file for now but will you consider versioning you script in the future? 

```
[InvalidArgumentException]                                                                                                          
Could not find a version of package foroco/php-browser-detection matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.     
```                                                                       
Thank you in advance. 

YG

**Comment by foroco** [comment]
Hi, @younggrandpa 

Thanks for the issue. I will do the appropriate test.

**Comment by rvalitov** [comment]
I also get the same stability error.
@foroco no success in fixing that?

**Comment by foroco** [comment]
@younggrandpa @rvalitov 

Hi, seems to be fixed.
My tests succeeded :)
