### ISSUE TITLE
Chrome 111 detected as Chrome 0

### ISSUE THREAD

**Issue by starinacool** [foroco/php-browser-detection#21]

**Comment by OleksiyOleksiyovych** [comment]
I have the same issue.

**The reason for the issue:** 
`if (intval($this->result_browser_version)>110 && !$this->match_ua('FBAV/|FBSV/|GSA/|Instagram')) $this->result_browser_version = 0;`
[line #1294](https://github.com/foroco/php-browser-detection/blob/master/src/BrowserDetection.php#L1294)

**Possible fix №1**
Remove line with check

**Possible fix №2**
Add "Chrome" to check `$this->match_ua('FBAV/|FBSV/|GSA/|Instagram/|Chrome')`

**Comment by foroco** [comment]
Hi,

Sorry about that weird bug...
Fixed (see new release).

Restricting detectable browser versions is necessary to avoid installing impossible versions.
For example in userAgent part: `... SomeBrowser/2023.03 ...`
