### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Rakreo** [foroco/php-browser-detection#25]
Would it be possible to also detect "Crawlers/Robots".....

Here are a few "User-Agents" from one of my server logs....

Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +http://megaindex.com/crawler)
CCBot/2.0 (https://commoncrawl.org/faq/)
Mozilla/5.0 (X11; compatible; semantic-visions.com crawler; HTTPClient 3.1)
Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)
mozilla/5.0 (compatible; hubspot crawler; web-crawlers@hubspot.com; +@operator_contact_url@)
Mozilla/5.0 (compatible; Seekport Crawler; http://seekport.com/)
Y!J-ASR/1.0 crawler (https://www.yahoo-help.jp/app/answers/detail/p/595/a_id/42716/)
Barkrowler/0.9 (+https://babbar.tech/crawler)
SearchAtlas.com SEO Crawler
MauiBot
Mozilla/5.0 (compatible; VelenPublicWebCrawler/1.0; +https://velen.io)
GarlikCrawler/1.2 (http://garlik.com/, crawler@garlik.com)
MauiBot (crawler.feedback+wc@gmail.com)
pimeyes.com crawler
Mozilla/5.0 (compatible; Barkrowler/0.9; +https://babbar.tech/crawler)
Mozilla/5.0 (compatible; MixrankBot; crawler@mixrank.com)
netEstate NE Crawler (+http://www.website-datenbank.de/)
SiteCheckerBotCrawler/1.0 (+http://sitechecker.pro)
MTRobot/0.2 (Metrics Tools Analytics Crawler; https://metrics-tools.de/robot.html; crawler@metrics-tools.de)
crawler/js-crawler
Mozilla/5.0 (compatible; TombaPublicWebCrawler/1.0; +https://tombascraper.com)
LCC (+http://corpora.uni-leipzig.de/crawler_faq.html)
clark-crawler2/Nutch-1.19-SNAPSHOT

**Comment by demonych** [comment]
please add detection of UptimeRobot http://www.uptimerobot.com/
ua=
`Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)`
