### ISSUE TITLE
Mac OS Ventura 13.6 not correct detected?

### ISSUE THREAD

**Issue by gaffling** [foroco/php-browser-detection#26]
https://www.whatismybrowser.com/detect/what-is-my-user-agent/

say my user_agent is:

[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

and your Script says:  MacOS Big Sur

any Ideas? Thanks a lot

PS: I run Mac OS Ventura 13.6 for sure!

**Comment by foroco** [comment]
Unfortunately, the major browser engines have "frozen" the OS version information in the User-Agent header.
For example, on macOS, the OS version information in the User-Agent is "frozen" at the macOS Big Sur release level (Mac OS X 10_15_7).
On Windows, the OS version information is "frozen" in the User-Agent at the Windows 10 release level (Windows NT 10.0).

Recent releases of WebKit, Chromium, and Gecko-based browsers no longer include current OS version information in the User-Agent header.

See reference:

https://issues.chromium.org/issues/40167872
https://bugzilla.mozilla.org/show_bug.cgi?id=1679929
https://bugs.webkit.org/show_bug.cgi?id=217364

One approach is to use the HTTP Client Hints headers, specifically the Sec-CH-UA-Platform-Version header. It's important to note, however, that only Chromium-based browsers currently support sending Client Hints headers.

**Comment by gaffling** [comment]
Many thanks for the detailed information
