### ISSUE TITLE
In windows 11 user agent always is "Windows NT 10.0"

### ISSUE THREAD

**Issue by Chiwa1024** [foroco/php-browser-detection#27]
## In windows 11 user agent always is "Windows NT 10.0"

If you want to read the "Sec-CH-UA-Platform-Version" header

1. The server needs set `header("accept-ch: Sec-Ch-Ua-Platform, Sec-Ch-Ua-Platform-Version") ; `
2. Subsequent requests will have `Sec-CH-UA-Platform` and `Sec-CH-UA-Platform-Version` headers.
3. Check header: `Sec-CH-UA-Platform` = "Windows" and `Sec-CH-UA-Platform-Version` >= 13

Related links
https://learn.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11

## This is an example:

```php
<?php
header("accept-ch: Sec-Ch-Ua-Platform, Sec-Ch-Ua-Platform-Version");

function isWin11(){
    if(isset($_SERVER['HTTP_SEC_CH_UA_PLATFORM']) &&
            $_SERVER['HTTP_SEC_CH_UA_PLATFORM'] == '"Windows"' && 
            isset($_SERVER['HTTP_SEC_CH_UA_PLATFORM_VERSION'])){

        if(13 <= intval(explode(".", preg_replace('/^"|"$/i', "", $_SERVER['HTTP_SEC_CH_UA_PLATFORM_VERSION']))[0])){
            return true;
        }

    }
    return false;
}

echo isWin11();
```

### Test environment:
Sccess
✅ Windows 11 ; Chrome/117
✅ Windows 11 ; Edge/117

Not support
❌ Windows 11 ; Firefox/113

**Comment by foroco** [comment]
I have been researching this issue:

Unfortunately, the major browser engines have "frozen" the OS version information in the User-Agent header.
For example, on macOS, the OS version information in the User-Agent is "frozen" at the macOS Big Sur release level (Mac OS X 10_15_7).
On Windows, the OS version information is "frozen" in the User-Agent at the Windows 10 release level (Windows NT 10.0).

Recent releases of WebKit, Chromium, and Gecko-based browsers no longer include current OS version information in the User-Agent header.

See reference:

https://issues.chromium.org/issues/40167872
https://bugzilla.mozilla.org/show_bug.cgi?id=1679929
https://bugs.webkit.org/show_bug.cgi?id=217364

One approach is to use the HTTP Client Hints headers, specifically the Sec-CH-UA-Platform-Version header. It's important to note, however, that only Chromium-based browsers currently support sending Client Hints headers.
