### ISSUE TITLE
"Trying to access array offset on value of type bool"

### ISSUE THREAD

**Issue by lonnylot** [foroco/php-browser-detection#7]
On PHP 7.4.22 calling `getDevice` on `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Silk/60.2.12 like Chrome/60.0.3112.107 Safari/537.36` results in:

```bash
Notice: Trying to access array offset on value of type bool in /.../vendor/foroco/php-browser-detection/src/BrowserDetection.php on line 587
```

**Comment by foroco** [comment]
Hi @lonnylot 
Fixed in v2.3
This Warning Notice appears since PHP version 7.4.
Thank you for participating!
